# create readthedocs config
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

# build documentation in the meps/ directory with Sphinx
sphinx:
  configuration: meps/conf.py
  fail_on_warning: true

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: docs-requirements.txt
