# create readthedocs config
# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

sphinx:
  configuration: docs/conf.py
  builder: dirhtml

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
