name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs-requirements.txt
    - name: Build documentation
      run: sphinx-build -nW --keep-going -b html meps meps/_build/html

  # activate after moved repository
  # links-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.9
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r docs-requirements.txt
  #   - name: Check links
  #     run: sphinx-build -nW --keep-going -b linkcheck meps meps/_build/linkcheck
